#!/usr/bin/env bash
# Source this file to install and activate the virtual environment from scratch
VENV=.venv

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

# Process flags
EXTRA_ARGS_UV_SYNC=
EXTRA_ARGS_UV_VENV=
for arg in "$@"; do
  case $arg in
        --clean|--clear)
            EXTRA_ARGS_UV_VENV="$EXTRA_ARGS_UV_VENV --clear"
            ;;
        --upgrade)
            EXTRA_ARGS_UV_SYNC="$EXTRA_ARGS_UV_SYNC --upgrade"
            ;;
        *)
            echo "Unknown argument: $arg"
            echo "Usage: source ${BASH_SOURCE[0]} [--clean] [--upgrade]"
            return 1
            ;;
    esac
done

uv --project="$SCRIPT_DIR" venv --allow-existing $EXTRA_ARGS_UV_VENV
uv --project="$SCRIPT_DIR" sync --all-extras $UV_SYNC_EXTRA_ARGS
uv --project="$SCRIPT_DIR" run pre-commit install
. "$SCRIPT_DIR/$VENV/bin/activate"
